const products = [
    {
        _id: '1',
        name: 'vintage shirt',
        image: '/images/v1.jpg',
        description:'This is a mix of different styles men shirts.You might find some modern shirts in the mix.',
        brand:'vemo',
        category:'Clothing',
        price: 12.95,
        countInStock:7,
        rating:4.5,
        numReviews:4,
    },
    {
        _id: '2',
        name: 'vintage shirt',
        image: '/images/v2.jpg',
        description:'This is a mix of different styles men shirts.You might find some modern shirts in the mix.',
        brand:'vemo',
        category:'Clothing',
        price: 12.95,
        countInStock:7,
        rating:3,
        numReviews:4,
    },
    {
        _id: '3',
        name: 'vintage shirt',
        image: '/images/v3.jpg',
        description:'This is a mix of different styles men shirts.You might find some modern shirts in the mix.',
        brand:'vemo',
        category:'Clothing',
        price: 12.95,
        countInStock:7,
        rating:2.5,
        numReviews:4,
    },
    {
        _id: '4',
        name: 'vintage shirt',
        image: '/images/va1.jpg',
        description:'This is a mix of different styles men shirts.You might find some modern shirts in the mix.',
        brand:'vemo',
        category:'Clothing',
        price: 12.95,
        countInStock:7,
        rating:6,
        numReviews:4,
    },
    {
        _id: '5',
        name: 'vintage hat',
        image: '/images/hat.jpg',
        description:'This is a mix of different styles men shirts.You might find some modern shirts in the mix.',
        brand:'vemo',
        category:'Hart',
        price: 12.95,
        countInStock:7,
        rating:4,
        numReviews:4,
    },
    {
        _id: '6',
        name: 'vintage skat',
        image: '/images/ima.jpg',
        description:'This is a mix of different styles men shirts.You might find some modern shirts in the mix.',
        brand:'vemo',
        category:'Clothing',
        price: 12.95,
        countInStock:7,
        rating:4.9,
        numReviews:4,
    }
]

export default products